# Generated by Django 5.1.1 on 2024-09-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("histories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbgeneralhandstats",
            name="chips_difference",
            field=models.DecimalField(
                db_column="chips_difference",
                db_comment="The difference in chips the player has after rewarding",
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="chips_difference",
            ),
        ),
    ]
