# Generated by Django 5.1.1 on 2024-09-11 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("histories", "0003_dbgeneralhandstats_chips_difference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbplayerhandstats",
            name="flop_stats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flop_stats",
                to="histories.dbflophandstats",
            ),
        ),
        migrations.AlterField(
            model_name="dbplayerhandstats",
            name="general_stats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_stats",
                to="histories.dbgeneralhandstats",
            ),
        ),
        migrations.AlterField(
            model_name="dbplayerhandstats",
            name="preflop_stats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preflop_stats",
                to="histories.dbpreflophandstats",
            ),
        ),
        migrations.AlterField(
            model_name="dbplayerhandstats",
            name="river_stats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="river_stats",
                to="histories.dbriverhandstats",
            ),
        ),
        migrations.AlterField(
            model_name="dbplayerhandstats",
            name="turn_stats",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turn_stats",
                to="histories.dbturnhandstats",
            ),
        ),
    ]
