# Generated by Django 5.1.1 on 2024-09-13 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("histories", "0004_alter_dbplayerhandstats_flop_stats_and_more"),
        ("players", "0003_dbplayerstats_pfr_vpip_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbflophandstats",
            name="player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.dbplayer",
            ),
        ),
        migrations.AddField(
            model_name="dbgeneralhandstats",
            name="player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.dbplayer",
            ),
        ),
        migrations.AddField(
            model_name="dbpreflophandstats",
            name="player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.dbplayer",
            ),
        ),
        migrations.AddField(
            model_name="dbriverhandstats",
            name="player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.dbplayer",
            ),
        ),
        migrations.AddField(
            model_name="dbturnhandstats",
            name="player",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="players.dbplayer",
            ),
        ),
    ]
