# Generated by Django 5.1.1 on 2024-09-13 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("histories", "0006_dbflophandstats_hand_history_and_more"),
        ("players", "0003_dbplayerstats_pfr_vpip_ratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbflophandstats",
            name="hand_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
        migrations.AlterField(
            model_name="dbflophandstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.dbplayer"
            ),
        ),
        migrations.AlterField(
            model_name="dbgeneralhandstats",
            name="hand_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
        migrations.AlterField(
            model_name="dbgeneralhandstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.dbplayer"
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflophandstats",
            name="hand_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflophandstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.dbplayer"
            ),
        ),
        migrations.AlterField(
            model_name="dbriverhandstats",
            name="hand_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
        migrations.AlterField(
            model_name="dbriverhandstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.dbplayer"
            ),
        ),
        migrations.AlterField(
            model_name="dbturnhandstats",
            name="hand_history",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
        migrations.AlterField(
            model_name="dbturnhandstats",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="players.dbplayer"
            ),
        ),
    ]
