# Generated by Django 5.1.1 on 2024-09-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("histories", "0007_alter_dbflophandstats_hand_history_and_more"),
        ("players", "0003_dbplayerstats_pfr_vpip_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbgeneralhandstats",
            name="bounty",
            field=models.DecimalField(
                db_column="bounty",
                db_comment="The current bounty on the player",
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="bounty",
            ),
        ),
        migrations.AddField(
            model_name="dbgeneralhandstats",
            name="position",
            field=models.ForeignKey(
                db_column="position",
                db_comment="The position of the player",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="position",
                to="players.dbposition",
                verbose_name="position",
            ),
        ),
        migrations.AddField(
            model_name="dbgeneralhandstats",
            name="seat",
            field=models.PositiveSmallIntegerField(
                db_column="seat",
                db_comment="The seat number of the player",
                default=0,
                verbose_name="seat",
            ),
        ),
    ]
