# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from .unstable_finetune_create_request_overrides_batch_size import UnstableFinetuneCreateRequestOverridesBatchSize
from .unstable_finetune_create_request_overrides_preference_variant import (
    UnstableFinetuneCreateRequestOverridesPreferenceVariant,
)

try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic  # type: ignore


class UnstableFinetuneCreateRequestOverrides(pydantic.BaseModel):
    batch_size: typing.Optional[UnstableFinetuneCreateRequestOverridesBatchSize]
    learning_rate_multiplier: typing.Optional[float]
    num_epochs: typing.Optional[float]
    preference_variant: typing.Optional[UnstableFinetuneCreateRequestOverridesPreferenceVariant]
    preference_learning_rate_multiplier: typing.Optional[float]
    preference_num_epochs: typing.Optional[float]
    preference_training_beta: typing.Optional[float]
    preference_adapter_weight: typing.Optional[float]
    is_preference_tuning_enabled: typing.Optional[str]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        smart_union = True
        json_encoders = {dt.datetime: serialize_datetime}
