# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rbt/memoize/v1/memoize.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from rbt.v1alpha1 import options_pb2 as rbt_dot_v1alpha1_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1crbt/memoize/v1/memoize.proto\x12\x0erbt.memoize.v1\x1a\x1arbt/v1alpha1/options.proto\">\n\x07Memoize\x12\x0f\n\x07started\x18\x01 \x01(\x08\x12\x0e\n\x06stored\x18\x02 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c:\x04\x82\xb5\x18\x00\"\x0e\n\x0cResetRequest\"\x0f\n\rResetResponse\"\x0e\n\x0cStartRequest\"\x0f\n\rStartResponse\"\x1c\n\x0cStoreRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x0f\n\rStoreResponse\"\x0f\n\rStatusRequest\"?\n\x0eStatusResponse\x12\x0f\n\x07started\x18\x01 \x01(\x08\x12\x0e\n\x06stored\x18\x02 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x32\xcd\x02\n\x10MemoizeInterface\x12L\n\x05Reset\x12\x1c.rbt.memoize.v1.ResetRequest\x1a\x1d.rbt.memoize.v1.ResetResponse\"\x06\x82\xb5\x18\x02\x12\x00\x12L\n\x05Start\x12\x1c.rbt.memoize.v1.StartRequest\x1a\x1d.rbt.memoize.v1.StartResponse\"\x06\x82\xb5\x18\x02\x12\x00\x12L\n\x05Store\x12\x1c.rbt.memoize.v1.StoreRequest\x1a\x1d.rbt.memoize.v1.StoreResponse\"\x06\x82\xb5\x18\x02\x12\x00\x12O\n\x06Status\x12\x1d.rbt.memoize.v1.StatusRequest\x1a\x1e.rbt.memoize.v1.StatusResponse\"\x06\x82\xb5\x18\x02\n\x00\x62\x06proto3')



_MEMOIZE = DESCRIPTOR.message_types_by_name['Memoize']
_RESETREQUEST = DESCRIPTOR.message_types_by_name['ResetRequest']
_RESETRESPONSE = DESCRIPTOR.message_types_by_name['ResetResponse']
_STARTREQUEST = DESCRIPTOR.message_types_by_name['StartRequest']
_STARTRESPONSE = DESCRIPTOR.message_types_by_name['StartResponse']
_STOREREQUEST = DESCRIPTOR.message_types_by_name['StoreRequest']
_STORERESPONSE = DESCRIPTOR.message_types_by_name['StoreResponse']
_STATUSREQUEST = DESCRIPTOR.message_types_by_name['StatusRequest']
_STATUSRESPONSE = DESCRIPTOR.message_types_by_name['StatusResponse']
Memoize = _reflection.GeneratedProtocolMessageType('Memoize', (_message.Message,), {
  'DESCRIPTOR' : _MEMOIZE,
  '__module__' : 'rbt.memoize.v1.memoize_pb2'
  # @@protoc_insertion_point(class_scope:rbt.memoize.v1.Memoize)
  })
_sym_db.RegisterMessage(Memoize)

ResetRequest = _reflection.GeneratedProtocolMessageType('ResetRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESETREQUEST,
  '__module__' : 'rbt.memoize.v1.memoize_pb2'
  # @@protoc_insertion_point(class_scope:rbt.memoize.v1.ResetRequest)
  })
_sym_db.RegisterMessage(ResetRequest)

ResetResponse = _reflection.GeneratedProtocolMessageType('ResetResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESETRESPONSE,
  '__module__' : 'rbt.memoize.v1.memoize_pb2'
  # @@protoc_insertion_point(class_scope:rbt.memoize.v1.ResetResponse)
  })
_sym_db.RegisterMessage(ResetResponse)

StartRequest = _reflection.GeneratedProtocolMessageType('StartRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTREQUEST,
  '__module__' : 'rbt.memoize.v1.memoize_pb2'
  # @@protoc_insertion_point(class_scope:rbt.memoize.v1.StartRequest)
  })
_sym_db.RegisterMessage(StartRequest)

StartResponse = _reflection.GeneratedProtocolMessageType('StartResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTRESPONSE,
  '__module__' : 'rbt.memoize.v1.memoize_pb2'
  # @@protoc_insertion_point(class_scope:rbt.memoize.v1.StartResponse)
  })
_sym_db.RegisterMessage(StartResponse)

StoreRequest = _reflection.GeneratedProtocolMessageType('StoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _STOREREQUEST,
  '__module__' : 'rbt.memoize.v1.memoize_pb2'
  # @@protoc_insertion_point(class_scope:rbt.memoize.v1.StoreRequest)
  })
_sym_db.RegisterMessage(StoreRequest)

StoreResponse = _reflection.GeneratedProtocolMessageType('StoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _STORERESPONSE,
  '__module__' : 'rbt.memoize.v1.memoize_pb2'
  # @@protoc_insertion_point(class_scope:rbt.memoize.v1.StoreResponse)
  })
_sym_db.RegisterMessage(StoreResponse)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _STATUSREQUEST,
  '__module__' : 'rbt.memoize.v1.memoize_pb2'
  # @@protoc_insertion_point(class_scope:rbt.memoize.v1.StatusRequest)
  })
_sym_db.RegisterMessage(StatusRequest)

StatusResponse = _reflection.GeneratedProtocolMessageType('StatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _STATUSRESPONSE,
  '__module__' : 'rbt.memoize.v1.memoize_pb2'
  # @@protoc_insertion_point(class_scope:rbt.memoize.v1.StatusResponse)
  })
_sym_db.RegisterMessage(StatusResponse)

_MEMOIZEINTERFACE = DESCRIPTOR.services_by_name['MemoizeInterface']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEMOIZE._options = None
  _MEMOIZE._serialized_options = b'\202\265\030\000'
  _MEMOIZEINTERFACE.methods_by_name['Reset']._options = None
  _MEMOIZEINTERFACE.methods_by_name['Reset']._serialized_options = b'\202\265\030\002\022\000'
  _MEMOIZEINTERFACE.methods_by_name['Start']._options = None
  _MEMOIZEINTERFACE.methods_by_name['Start']._serialized_options = b'\202\265\030\002\022\000'
  _MEMOIZEINTERFACE.methods_by_name['Store']._options = None
  _MEMOIZEINTERFACE.methods_by_name['Store']._serialized_options = b'\202\265\030\002\022\000'
  _MEMOIZEINTERFACE.methods_by_name['Status']._options = None
  _MEMOIZEINTERFACE.methods_by_name['Status']._serialized_options = b'\202\265\030\002\n\000'
  _MEMOIZE._serialized_start=76
  _MEMOIZE._serialized_end=138
  _RESETREQUEST._serialized_start=140
  _RESETREQUEST._serialized_end=154
  _RESETRESPONSE._serialized_start=156
  _RESETRESPONSE._serialized_end=171
  _STARTREQUEST._serialized_start=173
  _STARTREQUEST._serialized_end=187
  _STARTRESPONSE._serialized_start=189
  _STARTRESPONSE._serialized_end=204
  _STOREREQUEST._serialized_start=206
  _STOREREQUEST._serialized_end=234
  _STORERESPONSE._serialized_start=236
  _STORERESPONSE._serialized_end=251
  _STATUSREQUEST._serialized_start=253
  _STATUSREQUEST._serialized_end=268
  _STATUSRESPONSE._serialized_start=270
  _STATUSRESPONSE._serialized_end=333
  _MEMOIZEINTERFACE._serialized_start=336
  _MEMOIZEINTERFACE._serialized_end=669
# @@protoc_insertion_point(module_scope)
