
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-23T05:18:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "a620e4da106b570cd6d7b5b772ef57593543495b",
 "version": "2024.9.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
