# Generated by ariadne-codegen
# Source: ../graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import CheckResultEnum


class DeviceGroupElastic(BaseModel):
    groups_elastic: Optional["DeviceGroupElasticGroupsElastic"] = Field(
        alias="groupsElastic"
    )


class DeviceGroupElasticGroupsElastic(BaseModel):
    total_count: Optional[int] = Field(alias="totalCount")
    results: Optional[List[Optional["DeviceGroupElasticGroupsElasticResults"]]]


class DeviceGroupElasticGroupsElasticResults(BaseModel):
    id: str
    name: Optional[str]
    title: Optional[str]
    description: Optional[str]
    location: Optional["DeviceGroupElasticGroupsElasticResultsLocation"]
    device_count: Optional[int] = Field(alias="deviceCount")
    permission: Optional[int]
    checks: Optional[Any]
    facts: Optional[Any]
    check_elements: Optional[
        List[Optional["DeviceGroupElasticGroupsElasticResultsCheckElements"]]
    ] = Field(alias="checkElements")


class DeviceGroupElasticGroupsElasticResultsLocation(BaseModel):
    id: str
    address: Optional[str]
    city: Optional[str]
    zip_code: Optional[str] = Field(alias="zipCode")
    lon: Optional[float]
    lat: Optional[float]


class DeviceGroupElasticGroupsElasticResultsCheckElements(BaseModel):
    id: str
    key: Optional[str]
    reason: Optional[str]
    result: Optional[CheckResultEnum]
    metrics: Optional[Any]
    neops_task: Optional[
        "DeviceGroupElasticGroupsElasticResultsCheckElementsNeopsTask"
    ] = Field(alias="neopsTask")


class DeviceGroupElasticGroupsElasticResultsCheckElementsNeopsTask(BaseModel):
    id: str
    name: Optional[str]


DeviceGroupElastic.model_rebuild()
DeviceGroupElasticGroupsElastic.model_rebuild()
DeviceGroupElasticGroupsElasticResults.model_rebuild()
DeviceGroupElasticGroupsElasticResultsCheckElements.model_rebuild()
