
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-21T06:49:45+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "eba96d29b02fcada4defee0c6d02674c2d2f205c",
 "version": "0.0.29"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
