# Generated by Django 5.1.1 on 2024-09-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0002_dbplayerstats_cnt_pfr_opp"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbplayerstats",
            name="pfr_vpip_ratio",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
