# Generated by Django 5.1.1 on 2024-09-18 11:39

import pkrdatamapper.common.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0008_alter_dbflopplayerstats_cnt_3bet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbplayerstats",
            name="cnt_hands_played_2",
            field=pkrdatamapper.common.fields.CountField(default=0),
        ),
    ]
