# Generated by Django 5.1.1 on 2024-09-18 11:52

import pkrdatamapper.common.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0009_dbplayerstats_cnt_hands_played_2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbplayerstats",
            name="cnt_hands_played_2",
        ),
        migrations.RemoveField(
            model_name="dbplayerstats",
            name="cnt_pfr",
        ),
        migrations.RemoveField(
            model_name="dbplayerstats",
            name="cnt_pfr_opp",
        ),
        migrations.RemoveField(
            model_name="dbplayerstats",
            name="cnt_vpip",
        ),
        migrations.RemoveField(
            model_name="dbplayerstats",
            name="pfr",
        ),
        migrations.RemoveField(
            model_name="dbplayerstats",
            name="pfr_vpip_ratio",
        ),
        migrations.RemoveField(
            model_name="dbplayerstats",
            name="vpip",
        ),
        migrations.AlterField(
            model_name="dbplayerstats",
            name="cnt_hands_played",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Number of hands played", default=0
            ),
        ),
    ]
