# Generated by Django 4.1.4 on 2023-01-04 08:41

from django.db import migrations

import privates.fields
import privates.storages

import simple_certmanager.validators


class Migration(migrations.Migration):
    dependencies = [
        ("simple_certmanager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="private_key",
            field=privates.fields.PrivateMediaFileField(
                blank=True,
                help_text="The content of the private key",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="ssl_certs_keys/%Y/%m/%d",
                validators=[simple_certmanager.validators.PrivateKeyValidator()],
                verbose_name="private key",
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="public_certificate",
            field=privates.fields.PrivateMediaFileField(
                help_text="The content of the certificate",
                storage=privates.storages.PrivateMediaFileSystemStorage(),
                upload_to="ssl_certs_keys/%Y/%m/%d",
                validators=[simple_certmanager.validators.PublicCertValidator()],
                verbose_name="public certificate",
            ),
        ),
    ]
