# Generated by Django 4.2.14 on 2024-08-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simple_certmanager", "0004_signingrequest_public_certificate"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="signingrequest",
            name="csr_and_private_key_must_be_set_together",
        ),
    ]
