# Generated by Django 4.2.14 on 2024-07-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simple_certmanager", "0003_signingrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="signingrequest",
            name="public_certificate",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signing_request",
                to="simple_certmanager.certificate",
            ),
        ),
    ]
