# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .note_update_params import NoteUpdateParams as NoteUpdateParams
from .service_update_params import ServiceUpdateParams as ServiceUpdateParams
from .attribute_create_params import AttributeCreateParams as AttributeCreateParams
from .attribute_update_params import AttributeUpdateParams as AttributeUpdateParams
from .location_category_update_params import LocationCategoryUpdateParams as LocationCategoryUpdateParams
from .supported_currency_update_params import SupportedCurrencyUpdateParams as SupportedCurrencyUpdateParams
from .supported_language_update_params import SupportedLanguageUpdateParams as SupportedLanguageUpdateParams
from .accessibility_feature_update_params import AccessibilityFeatureUpdateParams as AccessibilityFeatureUpdateParams
