
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-20T16:58:06+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5de46e94c23785fa7e17e3e1d00c3afb6cb1c919",
 "version": "0.15.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
