# Generated by Django 5.1.1 on 2024-09-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbtournament",
            name="bounty_won",
            field=models.FloatField(
                db_comment="The amount of bounties won by hero", default=0.0
            ),
        ),
    ]
