
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-20T15:41:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9392277c6d10a20d6b6d2965f73b1250fbe0fab1",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
