
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-19T09:46:54+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "88f089ab6d436a33476b53edcba56027906b843c",
 "version": "2.3.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
