
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-20T17:21:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b4e014f2001d57284659a686651ead1c35fb955a",
 "version": "2.45.3b0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
