# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/terraquantum/group/v1/group/list_groups_by_ids_request.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@com/terraquantum/group/v1/group/list_groups_by_ids_request.proto\x12\x1f\x63om.terraquantum.group.v1.group\"*\n\x16ListGroupsByIdsRequest\x12\x10\n\x03ids\x18\x01 \x03(\tR\x03idsB\xa9\x02\n#com.com.terraquantum.group.v1.groupB\x1bListGroupsByIdsRequestProtoP\x01ZCterraquantum.swiss/tq42_grpc_client/com/terraquantum/group/v1/group\xa2\x02\x05\x43TGVG\xaa\x02\x1f\x43om.Terraquantum.Group.V1.Group\xca\x02\x1f\x43om\\Terraquantum\\Group\\V1\\Group\xe2\x02+Com\\Terraquantum\\Group\\V1\\Group\\GPBMetadata\xea\x02#Com::Terraquantum::Group::V1::Groupb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.terraquantum.group.v1.group.list_groups_by_ids_request_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#com.com.terraquantum.group.v1.groupB\033ListGroupsByIdsRequestProtoP\001ZCterraquantum.swiss/tq42_grpc_client/com/terraquantum/group/v1/group\242\002\005CTGVG\252\002\037Com.Terraquantum.Group.V1.Group\312\002\037Com\\Terraquantum\\Group\\V1\\Group\342\002+Com\\Terraquantum\\Group\\V1\\Group\\GPBMetadata\352\002#Com::Terraquantum::Group::V1::Group'
  _globals['_LISTGROUPSBYIDSREQUEST']._serialized_start=101
  _globals['_LISTGROUPSBYIDSREQUEST']._serialized_end=143
# @@protoc_insertion_point(module_scope)
