TABLE_START_ICON = "\u250c"
TABLE_SIDE_ICON = "\u2502"
TABLE_BRANCH_ICON = "\u251c"
TABLE_END_ICON = "\u2514"
RIGHT_ARROW_ICON = "\u2192"
BOX_ICON = "\u274f"
ENTER_ICON = "\u21b3"
CHECKMARK_ICON = "\u2713"

TABLE_PARTS_LIST = [
    TABLE_START_ICON,
    TABLE_SIDE_ICON,
    TABLE_BRANCH_ICON,
    TABLE_END_ICON,
]
