
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-22T15:53:31+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "349f91fde938e61eace6b972c478b2cf94f15e8e",
 "version": "0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
