
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-24T17:54:43+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "55f0a79c70caaca59b7f24b10cde0500dbe4e0e8",
 "version": "v0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
