# Generated by Django 4.2.11 on 2024-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[("OP", "Open"), ("CD", "Completed"), ("CL", "Cancelled")],
                db_index=True,
                help_text="Status of the Order request",
                max_length=2,
            ),
        ),
    ]
