
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-19T09:18:33+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e9921bd54544c29dc9bbf66c641b883073d3e30",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
