# coding: utf-8

"""
    SciCat backend API

    This is the API for the SciCat Backend ============================================

    The version of the OpenAPI document: 4.1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from Scicat-Python-SDK-test.models.user_settings import UserSettings

class TestUserSettings(unittest.TestCase):
    """UserSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSettings:
        """Test UserSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSettings`
        """
        model = UserSettings()
        if include_optional:
            return UserSettings(
                columns = [
                    None
                    ],
                dataset_count = 1.337,
                job_count = 1.337,
                user_id = ''
            )
        else:
            return UserSettings(
                columns = [
                    None
                    ],
                dataset_count = 1.337,
                job_count = 1.337,
                user_id = '',
        )
        """

    def testUserSettings(self):
        """Test UserSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
