# Generated by Django 5.1.1 on 2024-09-13 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("histories", "0005_dbflophandstats_player_dbgeneralhandstats_player_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbflophandstats",
            name="hand_history",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
        migrations.AddField(
            model_name="dbgeneralhandstats",
            name="hand_history",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
        migrations.AddField(
            model_name="dbpreflophandstats",
            name="hand_history",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
        migrations.AddField(
            model_name="dbriverhandstats",
            name="hand_history",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
        migrations.AddField(
            model_name="dbturnhandstats",
            name="hand_history",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="histories.dbhandhistory",
            ),
        ),
    ]
