
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-22T02:28:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d85038e6acf92febeacfc53463a7e70e35d82670",
 "version": "1.4.dev2438"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
