
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-19T13:50:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d7b0cb04ba79e391600d50e7a3992a22cb4db0b",
 "version": "0.7.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
