from __future__ import absolute_import, division, print_function

# Configuration variables

client_id = None
api_base = "https://api.1099policy.com"
api_key = "eyJraWQiOiIzcVFuU2JKQkFmOSs2WmluT1NNZWtVNmdRSmNudjUzSktIaEZSRGtRMFNVPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI4Yzc4OWYwMi0zY2JiLTRmYTctYTVjMi02ODFiMjliMTk1NDgiLCJhdWQiOiI0bmoyMmg4M2xmMnZxNDE2aGZmaTVjbDFlaiIsIndlYnNpdGUiOiJodHRwczpcL1wvZGFzaGJvYXJkLjEwOTlwb2xpY3kuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzI2NjU3ODg5LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9ITVlFa1dRd1AiLCJjb2duaXRvOnVzZXJuYW1lIjoiOGM3ODlmMDItM2NiYi00ZmE3LWE1YzItNjgxYjI5YjE5NTQ4IiwiZXhwIjoxNzI2OTExMTQzLCJpYXQiOjE3MjY4MjQ3NDMsImVtYWlsIjoiY2VtcmVAMTA5OXBvbGljeS5jb20ifQ.ywE188Fm_FNzcMpm-AffLZ7T9EfttQw_VOTtR5HBnW6BF2i3VgN41LDeVs5Mg-OMx8taKxJljN8IhTLSnGFEvakyUclxPCnbvutog_I_oDME0xyUrzlSz5iz3bsmDt1p6QpE3wtSHWxzxvewEAwe1uQE99UIh7PwNaGXU22CLZHPnEMFKV3p28TmQ01I9cMV_Z-ifGAdzvZfjyQAwUMNdyFLOHoKhd2vl61ub9tqsncOXneH-a2oCvF_D9XAXq-h01bA0iWY8v2J3Zh-DnWonq-ICsnojCwC4I0mKKI36NnzohERir5SWlZGbNs2AS_I_19j-MS49LewyJsIsGkHIw"
api_version = None
verify_ssl_certs = False
proxy = None
default_http_client = None
max_network_retries = 0
environment = "production"

# Set to either 'debug' or 'info', controls console logging
log = "debug"

# API resources
from ten99policy.api_resources import *  # noqa
