# Generated by Django 4.2.7 on 2024-09-20 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kernel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'verbose_name': '服务-客户',
                'verbose_name_plural': '服务-客户',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ERPSysRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('sys_registry', models.JSONField(blank=True, null=True, verbose_name='系统注册表')),
            ],
            options={
                'verbose_name': '系统注册表',
                'verbose_name_plural': '系统注册表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='描述表达式')),
                ('expression', models.CharField(blank=True, max_length=255, null=True, verbose_name='表达式')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='事件参数')),
            ],
            options={
                'verbose_name': '服务-事件',
                'verbose_name_plural': '服务-事件',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('sys_call', models.CharField(max_length=255, verbose_name='系统调用')),
                ('parameters', models.JSONField(blank=True, null=True, verbose_name='参数')),
            ],
            options={
                'verbose_name': '系统指令',
                'verbose_name_plural': '系统指令',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'verbose_name': '服务-人员',
                'verbose_name_plural': '服务-人员',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'verbose_name': '服务-组织',
                'verbose_name_plural': '服务-组织',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('pid', kernel.models.PidField(default=0, verbose_name='进程id')),
                ('state', models.CharField(choices=[('NEW', '新建'), ('READY', '就绪'), ('EXECUTING', '执行中'), ('WAITING', '等待'), ('TERMINATED', '终止')], default='NEW', max_length=50, verbose_name='状态')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='计划时间')),
                ('program', models.JSONField(blank=True, null=True, verbose_name='程序')),
                ('pc', models.PositiveIntegerField(blank=True, null=True, verbose_name='程序计数器')),
                ('registers', models.JSONField(blank=True, null=True, verbose_name='寄存器')),
                ('io_status', models.JSONField(blank=True, null=True, verbose_name='I/O状态')),
                ('cpu_scheduling', models.JSONField(blank=True, null=True, verbose_name='CPU调度')),
                ('accounting', models.JSONField(blank=True, null=True, verbose_name='帐务')),
                ('sp', models.PositiveIntegerField(blank=True, null=True, verbose_name='栈指针')),
                ('pcb', models.JSONField(blank=True, null=True, verbose_name='进程控制块')),
                ('stack', models.JSONField(blank=True, null=True, verbose_name='栈')),
                ('heap', models.JSONField(blank=True, null=True, verbose_name='堆')),
                ('schedule_context', models.JSONField(blank=True, null=True, verbose_name='调度上下文')),
                ('control_context', models.JSONField(blank=True, null=True, verbose_name='控制上下文')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='操作员')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_instances', to='kernel.process', verbose_name='父进程')),
            ],
            options={
                'verbose_name': '服务-进程',
                'verbose_name_plural': '服务-进程',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
            ],
            options={
                'verbose_name': '服务-资源',
                'verbose_name_plural': '服务-资源',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='配置')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SysParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('config', models.JSONField(blank=True, null=True, verbose_name='配置')),
                ('expires_in', models.PositiveIntegerField(default=8, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='计划时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='操作员')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.process', verbose_name='进程')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='服务项目')),
            ],
            options={
                'verbose_name': '进程工单',
                'verbose_name_plural': '进程工单',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('stack', models.JSONField(blank=True, null=True, verbose_name='栈')),
                ('heap', models.JSONField(blank=True, null=True, verbose_name='堆')),
                ('sp', models.PositiveIntegerField(blank=True, null=True, verbose_name='栈指针')),
                ('updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kernel.process', verbose_name='进程')),
            ],
            options={
                'verbose_name': '进程栈',
                'verbose_name_plural': '进程栈',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('parameter_values', models.JSONField(blank=True, null=True, verbose_name='参数值')),
                ('order', models.SmallIntegerField(default=0, verbose_name='顺序')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.event', verbose_name='事件')),
                ('next_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruled_as_next_service', to='kernel.service', verbose_name='后续服务')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='服务')),
                ('system_operand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.instruction', verbose_name='系统指令')),
            ],
            options={
                'verbose_name': '服务-规则',
                'verbose_name_plural': '服务-规则',
                'ordering': ['event', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='中文名称')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('pym', models.CharField(blank=True, max_length=255, null=True, verbose_name='拼音码')),
                ('erpsys_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ERPSysID')),
                ('service_items', models.ManyToManyField(blank=True, related_name='roles', to='kernel.service', verbose_name='服务项目')),
            ],
            options={
                'verbose_name': '服务-角色',
                'verbose_name_plural': '服务-角色',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='process',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='服务'),
        ),
        migrations.AddField(
            model_name='operator',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.organization', verbose_name='组织'),
        ),
        migrations.AddField(
            model_name='operator',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.role', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='operator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
