
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-23T12:39:06-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "fbbc75723989bfc0129c7eeb5280666f40cf9f88",
 "version": "1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
