
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-23T17:09:09-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "0a0ea4f400ca6d1e10ad3b154f902e637a5d6447",
 "version": "2.45.3b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
