__title__ = "graphene_disable_introspection"
__description__ = "Middleware for Python Graphene to disable introspection"
__version__ = "0.2"
__author__ = "Carlo Völker"
__author_email__ = "carlovoelker@gmx.net"
__license__ = "GPL-3.0"
__url__ = "https://github.com/Paprikaschote/graphene-disable-introspection"
