
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-24T11:21:44+0530",
 "dirty": false,
 "error": null,
 "full-revisionid": "7dda84c1cf42db55ae772369a7115506ecdebd03",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
