# Code generated by TRAC

from __future__ import annotations
import typing as _tp  # noqa
import dataclasses as _dc  # noqa
import enum as _enum  # noqa


@_dc.dataclass
class _ConfigFile:

    config: _tp.Dict[str, str] = _dc.field(default_factory=dict)


@_dc.dataclass
class PluginConfig:

    protocol: str = None

    properties: _tp.Dict[str, str] = _dc.field(default_factory=dict)

    secrets: _tp.Dict[str, str] = _dc.field(default_factory=dict)


@_dc.dataclass
class PlatformInfo:

    environment: str = None

    production: bool = None

    deploymentInfo: _tp.Dict[str, str] = _dc.field(default_factory=dict)


@_dc.dataclass
class AuthenticationConfig:

    jwtIssuer: str = None

    jwtExpiry: int = None

    jwtLimit: int = None

    jwtRefresh: int = None

    provider: _tp.Optional[PluginConfig] = None

    disableAuth: bool = None

    disableSigning: bool = None

    systemUserId: str = None

    systemUserName: str = None

    systemTicketDuration: int = None

    systemTicketRefresh: int = None


@_dc.dataclass
class StorageConfig:

    buckets: _tp.Dict[str, PluginConfig] = _dc.field(default_factory=dict)

    defaultBucket: str = None

    defaultFormat: str = None


@_dc.dataclass
class ServiceConfig:

    enabled: _tp.Optional[bool] = None

    alias: str = None

    port: int = None
