# Code generated by TRAC

from __future__ import annotations
import typing as _tp  # noqa
import dataclasses as _dc  # noqa
import enum as _enum  # noqa

from .common import *  # noqa



@_dc.dataclass
class RuntimeConfig:

    config: _tp.Dict[str, str] = _dc.field(default_factory=dict)

    storage: StorageConfig = None

    repositories: _tp.Dict[str, PluginConfig] = _dc.field(default_factory=dict)

    sparkSettings: SparkSettings = None

    runtimeApi: ServiceConfig = None


@_dc.dataclass
class SparkSettings:

    sparkProps: _tp.Dict[str, str] = _dc.field(default_factory=dict)
