
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-23T16:16:21-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "1af8d6b203c33fdc84a2887477b2b7cc5c6fb54f",
 "version": "1.9.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
