
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-23T22:45:10+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4da0654716b4bc9bd3d0b155925f8109b2b1efe",
 "version": "v0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
