# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protos.auth.auth_pb2 as auth__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckEmail = channel.unary_unary(
                '/AuthService/CheckEmail',
                request_serializer=auth__pb2.CheckEmailRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckEmailResponse.FromString,
                _registered_method=True)
        self.CheckCredentials = channel.unary_unary(
                '/AuthService/CheckCredentials',
                request_serializer=auth__pb2.CheckCredentialsRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckCredentialsResponse.FromString,
                _registered_method=True)
        self.CheckOtp = channel.unary_unary(
                '/AuthService/CheckOtp',
                request_serializer=auth__pb2.CheckOtpRequest.SerializeToString,
                response_deserializer=auth__pb2.CheckOtpResponse.FromString,
                _registered_method=True)
        self.ResetPassword = channel.unary_unary(
                '/AuthService/ResetPassword',
                request_serializer=auth__pb2.ResetPasswordRequest.SerializeToString,
                response_deserializer=auth__pb2.ResetPasswordResponse.FromString,
                _registered_method=True)
        self.ResetPasswordToken = channel.unary_unary(
                '/AuthService/ResetPasswordToken',
                request_serializer=auth__pb2.ResetPasswordTokenRequest.SerializeToString,
                response_deserializer=auth__pb2.ResetPasswordTokenResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOtp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetPasswordToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckEmail,
                    request_deserializer=auth__pb2.CheckEmailRequest.FromString,
                    response_serializer=auth__pb2.CheckEmailResponse.SerializeToString,
            ),
            'CheckCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCredentials,
                    request_deserializer=auth__pb2.CheckCredentialsRequest.FromString,
                    response_serializer=auth__pb2.CheckCredentialsResponse.SerializeToString,
            ),
            'CheckOtp': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOtp,
                    request_deserializer=auth__pb2.CheckOtpRequest.FromString,
                    response_serializer=auth__pb2.CheckOtpResponse.SerializeToString,
            ),
            'ResetPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPassword,
                    request_deserializer=auth__pb2.ResetPasswordRequest.FromString,
                    response_serializer=auth__pb2.ResetPasswordResponse.SerializeToString,
            ),
            'ResetPasswordToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetPasswordToken,
                    request_deserializer=auth__pb2.ResetPasswordTokenRequest.FromString,
                    response_serializer=auth__pb2.ResetPasswordTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AuthService/CheckEmail',
            auth__pb2.CheckEmailRequest.SerializeToString,
            auth__pb2.CheckEmailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AuthService/CheckCredentials',
            auth__pb2.CheckCredentialsRequest.SerializeToString,
            auth__pb2.CheckCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckOtp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AuthService/CheckOtp',
            auth__pb2.CheckOtpRequest.SerializeToString,
            auth__pb2.CheckOtpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AuthService/ResetPassword',
            auth__pb2.ResetPasswordRequest.SerializeToString,
            auth__pb2.ResetPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetPasswordToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/AuthService/ResetPasswordToken',
            auth__pb2.ResetPasswordTokenRequest.SerializeToString,
            auth__pb2.ResetPasswordTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
