# Generated by Django 3.2.12 on 2022-07-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_system', '0004_auto_20220723_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='is sent?'),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sent time'),
        ),
    ]
