# Generated by Django 3.2.12 on 2023-01-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification_system', '0005_auto_20220725_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='notification_events_recipients', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('contacts', models.ManyToManyField(blank=True, related_name='contact_groups', to='notification_system.Contact', verbose_name='contacts')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_groups', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='contact_groups',
            field=models.ManyToManyField(blank=True, related_name='notification_events', to='notification_system.ContactGroup', verbose_name='contact groups'),
        ),
    ]
