# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"Q\n\x11\x43heckEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x17\n\x0frequest_address\x18\x02 \x01(\t\x12\x14\n\x0crequest_host\x18\x03 \x01(\t\":\n\x12\x43heckEmailResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0blogin_token\x18\x02 \x01(\t\"x\n\x17\x43heckCredentialsRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05token\x18\x03 \x01(\t\x12\x17\n\x0frequest_address\x18\x04 \x01(\t\x12\x14\n\x0crequest_host\x18\x05 \x01(\t\"@\n\x18\x43heckCredentialsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0blogin_token\x18\x02 \x01(\t\"\\\n\x0f\x43heckOtpRequest\x12\x0b\n\x03otp\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x17\n\x0frequest_address\x18\x03 \x01(\t\x12\x14\n\x0crequest_host\x18\x04 \x01(\t\"!\n\x10\x43heckOtpResponse\x12\r\n\x05token\x18\x01 \x01(\t\";\n\x14ResetPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0crequest_host\x18\x05 \x01(\t\"8\n\x15ResetPasswordResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"`\n\x19ResetPasswordTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x13\n\x0btoken_email\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"=\n\x1aResetPasswordTokenResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xcd\x02\n\x0b\x41uthService\x12\x35\n\nCheckEmail\x12\x12.CheckEmailRequest\x1a\x13.CheckEmailResponse\x12G\n\x10\x43heckCredentials\x12\x18.CheckCredentialsRequest\x1a\x19.CheckCredentialsResponse\x12/\n\x08\x43heckOtp\x12\x10.CheckOtpRequest\x1a\x11.CheckOtpResponse\x12>\n\rResetPassword\x12\x15.ResetPasswordRequest\x1a\x16.ResetPasswordResponse\x12M\n\x12ResetPasswordToken\x12\x1a.ResetPasswordTokenRequest\x1a\x1b.ResetPasswordTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKEMAILREQUEST']._serialized_start=14
  _globals['_CHECKEMAILREQUEST']._serialized_end=95
  _globals['_CHECKEMAILRESPONSE']._serialized_start=97
  _globals['_CHECKEMAILRESPONSE']._serialized_end=155
  _globals['_CHECKCREDENTIALSREQUEST']._serialized_start=157
  _globals['_CHECKCREDENTIALSREQUEST']._serialized_end=277
  _globals['_CHECKCREDENTIALSRESPONSE']._serialized_start=279
  _globals['_CHECKCREDENTIALSRESPONSE']._serialized_end=343
  _globals['_CHECKOTPREQUEST']._serialized_start=345
  _globals['_CHECKOTPREQUEST']._serialized_end=437
  _globals['_CHECKOTPRESPONSE']._serialized_start=439
  _globals['_CHECKOTPRESPONSE']._serialized_end=472
  _globals['_RESETPASSWORDREQUEST']._serialized_start=474
  _globals['_RESETPASSWORDREQUEST']._serialized_end=533
  _globals['_RESETPASSWORDRESPONSE']._serialized_start=535
  _globals['_RESETPASSWORDRESPONSE']._serialized_end=591
  _globals['_RESETPASSWORDTOKENREQUEST']._serialized_start=593
  _globals['_RESETPASSWORDTOKENREQUEST']._serialized_end=689
  _globals['_RESETPASSWORDTOKENRESPONSE']._serialized_start=691
  _globals['_RESETPASSWORDTOKENRESPONSE']._serialized_end=752
  _globals['_AUTHSERVICE']._serialized_start=755
  _globals['_AUTHSERVICE']._serialized_end=1088
# @@protoc_insertion_point(module_scope)
