# Generated by Django 5.0.9 on 2024-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sop_voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemaintainer',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voicemaintainer',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='voicemaintainer',
            name='status',
            field=models.CharField(default='Unknown', max_length=30),
        ),
    ]
