# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/nm/set-switch-state-data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.zepben/protobuf/nm/set-switch-state-data.proto\x12\x12zepben.protobuf.nm\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n\x11SwitchStateUpdate\x12\x0c\n\x04mRID\x18\x01 \x01(\t\x12\x0f\n\x07setOpen\x18\x02 \x01(\x08\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampB/\n\x16\x63om.zepben.protobuf.nmP\x01\xaa\x02\x12Zepben.Protobuf.NMb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.nm.set_switch_state_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.zepben.protobuf.nmP\001\252\002\022Zepben.Protobuf.NM'
  _globals['_SWITCHSTATEUPDATE']._serialized_start=103
  _globals['_SWITCHSTATEUPDATE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
