# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/nm/set-switch-state.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from zepben.protobuf.nm import set_switch_state_requests_pb2 as zepben_dot_protobuf_dot_nm_dot_set__switch__state__requests__pb2
from zepben.protobuf.nm import set_switch_state_responses_pb2 as zepben_dot_protobuf_dot_nm_dot_set__switch__state__responses__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)zepben/protobuf/nm/set-switch-state.proto\x12\x12zepben.protobuf.nm\x1a\x32zepben/protobuf/nm/set-switch-state-requests.proto\x1a\x33zepben/protobuf/nm/set-switch-state-responses.proto2\x95\x01\n\x12SwitchStateService\x12\x7f\n\x16setCurrentSwitchStates\x12\x31.zepben.protobuf.nm.SetCurrentSwitchStatesRequest\x1a\x32.zepben.protobuf.nm.SetCurrentSwitchStatesResponseB/\n\x16\x63om.zepben.protobuf.nmP\x01\xaa\x02\x12Zepben.Protobuf.NMb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.nm.set_switch_state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.zepben.protobuf.nmP\001\252\002\022Zepben.Protobuf.NM'
  _globals['_SWITCHSTATESERVICE']._serialized_start=171
  _globals['_SWITCHSTATESERVICE']._serialized_end=320
# @@protoc_insertion_point(module_scope)
