# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/nm/set-switch-state-responses.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3zepben/protobuf/nm/set-switch-state-responses.proto\x12\x12zepben.protobuf.nm\"3\n\x1eSetCurrentSwitchStatesResponse\x12\x11\n\tmessageId\x18\x01 \x01(\x03\x42/\n\x16\x63om.zepben.protobuf.nmP\x01\xaa\x02\x12Zepben.Protobuf.NMb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zepben.protobuf.nm.set_switch_state_responses_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.zepben.protobuf.nmP\001\252\002\022Zepben.Protobuf.NM'
  _globals['_SETCURRENTSWITCHSTATESRESPONSE']._serialized_start=75
  _globals['_SETCURRENTSWITCHSTATESRESPONSE']._serialized_end=126
# @@protoc_insertion_point(module_scope)
