__name__ = 'nguyenpanda'
__version__ = '0.1.9.7'
__author__ = 'Nguyen Tuong Ha'
__email__ = 'hatuongnguyen0107@gmail.com'
__maintainer__ = 'nguyenpanda'
__maintainer_email__ = 'hatuongnguyen0107@gmail.com'
__description__ = ('Welcome to the world of \'nguyenpanda\', a Python library that brings you the essence of utility packages, '
                   'each named after animals, perfectly representing its unique domain.')
__url__ = 'https://github.com/nguyenpanda'
__python_requires__ = '>=3.9'
__src__ = 'https://github.com/nguyenpanda/PyPackages'
__license__ = 'MIT'
