data_ = [
    {
        "index": 0,
        "heroName": "Alucard",
        "imgUrl": "http://localhost:8501/app/static/heroes/Alucard.png",
        "skills": [
            {
                "skillNumber": "",
                "skillName": "Name Here",
                "data": [
                    {
                        "skillLvl": "skill level",
                        "titleDict": True,
                        "heroLevel": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
                    },
                ],
            },
        ],
    },
    {
        "index": 0,
        "heroName": "Alucard",
        "imgUrl": "http://localhost:8501/app/static/heroes/Alucard.png",
        "skills": [
            {
                "skillNumber": "Skill 1 and 2",
                "skillName": "Name Here",
                "data": [
                    {
                        "skillLvl": "1",
                        "heroLevel": [
                            { "heroLvl": 1, "active": True },
                            { "heroLvl": 2, "active": True },
                            { "heroLvl": 3, "active": True },
                            { "heroLvl": 4, "active": True },
                            { "heroLvl": 5, "active": True },
                            { "heroLvl": 6, "active": True },
                            { "heroLvl": 7, "active": True },
                            { "heroLvl": 8, "active": True },
                            { "heroLvl": 9, "active": True },
                            { "heroLvl": 10, "active": True },
                            { "heroLvl": 11, "active": True },
                            { "heroLvl": 12, "active": True },
                            { "heroLvl": 13, "active": True },
                            { "heroLvl": 14, "active": True },
                            { "heroLvl": 15, "active": True },
                        ],
                    },
                    {
                        "skillLvl": "2",
                        "heroLevel": [
                            { "heroLvl": 1, "active": False },
                            { "heroLvl": 2, "active": False },
                            { "heroLvl": 3, "active": True },
                            { "heroLvl": 4, "active": True },
                            { "heroLvl": 5, "active": True },
                            { "heroLvl": 6, "active": True },
                            { "heroLvl": 7, "active": True },
                            { "heroLvl": 8, "active": True },
                            { "heroLvl": 9, "active": True },
                            { "heroLvl": 10, "active": True },
                            { "heroLvl": 11, "active": True },
                            { "heroLvl": 12, "active": True },
                            { "heroLvl": 13, "active": True },
                            { "heroLvl": 14, "active": True },
                            { "heroLvl": 15, "active": True },
                        ],
                    },
                    {
                        "skillLvl": "3",
                        "heroLevel": [
                            { "heroLvl": 1, "active": False },
                            { "heroLvl": 2, "active": False },
                            { "heroLvl": 3, "active": False },
                            { "heroLvl": 4, "active": False },
                            { "heroLvl": 5, "active": True },
                            { "heroLvl": 6, "active": True },
                            { "heroLvl": 7, "active": True },
                            { "heroLvl": 8, "active": True },
                            { "heroLvl": 9, "active": True },
                            { "heroLvl": 10, "active": True },
                            { "heroLvl": 11, "active": True },
                            { "heroLvl": 12, "active": True },
                            { "heroLvl": 13, "active": True },
                            { "heroLvl": 14, "active": True },
                            { "heroLvl": 15, "active": True },
                        ],
                    },
                    {
                        "skillLvl": "4",
                        "heroLevel": [
                            { "heroLvl": 1, "active": False },
                            { "heroLvl": 2, "active": False },
                            { "heroLvl": 3, "active": False },
                            { "heroLvl": 4, "active": False },
                            { "heroLvl": 5, "active": False },
                            { "heroLvl": 6, "active": False },
                            { "heroLvl": 7, "active": True },
                            { "heroLvl": 8, "active": True },
                            { "heroLvl": 9, "active": True },
                            { "heroLvl": 10, "active": True },
                            { "heroLvl": 11, "active": True },
                            { "heroLvl": 12, "active": True },
                            { "heroLvl": 13, "active": True },
                            { "heroLvl": 14, "active": True },
                            { "heroLvl": 15, "active": True },
                        ],
                    },
                    {
                        "skillLvl": "5",
                        "heroLevel": [
                            { "heroLvl": 1, "active": False },
                            { "heroLvl": 2, "active": False },
                            { "heroLvl": 3, "active": False },
                            { "heroLvl": 4, "active": False },
                            { "heroLvl": 5, "active": False },
                            { "heroLvl": 6, "active": False },
                            { "heroLvl": 7, "active": False },
                            { "heroLvl": 8, "active": False },
                            { "heroLvl": 9, "active": True },
                            { "heroLvl": 10, "active": True },
                            { "heroLvl": 11, "active": True },
                            { "heroLvl": 12, "active": True },
                            { "heroLvl": 13, "active": True },
                            { "heroLvl": 14, "active": True },
                            { "heroLvl": 15, "active": True },
                        ],
                    },
                    {
                        "skillLvl": "6",
                        "heroLevel": [
                            { "heroLvl": 1, "active": False },
                            { "heroLvl": 2, "active": False },
                            { "heroLvl": 3, "active": False },
                            { "heroLvl": 4, "active": False },
                            { "heroLvl": 5, "active": False },
                            { "heroLvl": 6, "active": False },
                            { "heroLvl": 7, "active": False },
                            { "heroLvl": 8, "active": False },
                            { "heroLvl": 9, "active": False },
                            { "heroLvl": 10, "active": False },
                            { "heroLvl": 11, "active": True },
                            { "heroLvl": 12, "active": True },
                            { "heroLvl": 13, "active": True },
                            { "heroLvl": 14, "active": True },
                            { "heroLvl": 15, "active": True },
                        ],
                    },
                ],
            },
            {
                "skillNumber": "Skill 3",
                "skillName": "Name Here",
                "data": [
                    {
                        "skillLvl": "1",
                        "heroLevel": [
                            { "heroLvl": 1, "active": False },
                            { "heroLvl": 2, "active": False },
                            { "heroLvl": 3, "active": False },
                            { "heroLvl": 4, "active": True },
                            { "heroLvl": 5, "active": True },
                            { "heroLvl": 6, "active": True },
                            { "heroLvl": 7, "active": True },
                            { "heroLvl": 8, "active": True },
                            { "heroLvl": 9, "active": True },
                            { "heroLvl": 10, "active": True },
                            { "heroLvl": 11, "active": True },
                            { "heroLvl": 12, "active": True },
                            { "heroLvl": 13, "active": True },
                            { "heroLvl": 14, "active": True },
                            { "heroLvl": 15, "active": True },
                        ],
                    },
                    {
                        "skillLvl": "2",
                        "heroLevel": [
                            { "heroLvl": 1, "active": False },
                            { "heroLvl": 2, "active": False },
                            { "heroLvl": 3, "active": False },
                            { "heroLvl": 4, "active": False },
                            { "heroLvl": 5, "active": False },
                            { "heroLvl": 6, "active": False },
                            { "heroLvl": 7, "active": False },
                            { "heroLvl": 8, "active": True },
                            { "heroLvl": 9, "active": True },
                            { "heroLvl": 10, "active": True },
                            { "heroLvl": 11, "active": True },
                            { "heroLvl": 12, "active": True },
                            { "heroLvl": 13, "active": True },
                            { "heroLvl": 14, "active": True },
                            { "heroLvl": 15, "active": True },
                        ],
                    },
                    {
                        "skillLvl": "3",
                        "heroLevel": [
                            { "heroLvl": 1, "active": False },
                            { "heroLvl": 2, "active": False },
                            { "heroLvl": 3, "active": False },
                            { "heroLvl": 4, "active": False },
                            { "heroLvl": 5, "active": False },
                            { "heroLvl": 6, "active": False },
                            { "heroLvl": 7, "active": False },
                            { "heroLvl": 8, "active": False },
                            { "heroLvl": 9, "active": False },
                            { "heroLvl": 10, "active": False },
                            { "heroLvl": 11, "active": False },
                            { "heroLvl": 12, "active": True },
                            { "heroLvl": 13, "active": True },
                            { "heroLvl": 14, "active": True },
                            { "heroLvl": 15, "active": True },
                        ],
                    },
                ],
            },
        ],
    },
];