
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: src/python/arcor2_ur:arcor2_ur_dist

from setuptools import setup

setup(**{
    'author': 'Robo@FIT',
    'author_email': 'imaterna@fit.vut.cz',
    'classifiers': [
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
        'Programming Language :: Python :: 3.11',
        'Natural Language :: English',
        'Topic :: Scientific/Engineering',
    ],
    'description': 'ARCOR2 Universal Robots service',
    'entry_points': {
        'console_scripts': [
            'arcor2_ur = arcor2_ur.scripts.ur:main',
        ],
    },
    'install_requires': (
        'Flask~=3.0.3',
        'arcor2~=1.5.0',
    ),
    'license': 'LGPL',
    'long_description': """# arcor2_ur

Communicates over ROS 2 with Universal Robots (tested with UR5e).

## Environment variables

- `ARCOR2_UR_URL=http://0.0.0.0:5012` - by default, the service listens on port 5012.
- `ARCOR2_UR_DEBUG=1` - turns on debug logging.
# Changelog

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),

## [1.1.0] - 2024-09-23

### Changed
- Removed waiting after trajectory execution (probably useless).
- Ability to set movement velocity and payload (mass only).

## [1.0.0] - 2024-09-12

### Changed
- Initial release of the UR service.""",
    'long_description_content_type': 'text/markdown',
    'name': 'arcor2_ur',
    'namespace_packages': (
    ),
    'package_data': {
        'arcor2_ur': (
            'VERSION',
            'data/moveit.yaml',
            'py.typed',
        ),
    },
    'packages': (
        'arcor2_ur',
        'arcor2_ur.scripts',
    ),
    'python_requires': '==3.11.*',
    'version': '1.1.0',
})
