
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-20T17:25:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e864642c07dc0bee69e583b432148631b569e9b2",
 "version": "2.45.2rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
