KEY_VALUES_FOR_PARALLEL_LINES = [
    "Address",
    "(Address of Property)",
    "Associates Name",
    "Associates Email Address",
    "Address [REQUIRED]",
    "Buyer",
    "Borrower",
    "Buyer Signature",
    "Buyers Brokerage",
    "Buyers Designated Agent",
    "Buyers Attorney",
    "City",
    "City, State, Zip [REQUIRED]",
    "Cooperating Broker, if any",
    "Contact",
    "Contact License ID",
    "Contact WA License ID",
    "Cooperating Sales Associate, if any",
    "Date",
    "Date/Time",
    "Date of Offer",
    "Date of Acceptance",
    "Email Adress",
    "Escrow Agent",
    "E-mail",
    "Fax",
    "Home Phone",
    "Homeowners/Condo Association (if any)",
    "Listing Brokers Office Address",
    "Listing Associates Email Address",
    "Licensed Supervisor of Associate",
    "Listing Sales Associate",
    "Listing Associates Name",
    "Listing Broker",
    "Licensed Supervisor of Listing Associate",
    "License ID",
    "Licensed Supervisor of Selling Associate",
    "License No.",
    "Listing Broker Firm",
    "Loan Officer",
    "MLS #",
    "Mortgage Company",
    "Management Co./Other Contact",
    "Management Co./Other Contact E-mail",
    "Loan Officer E-mail",
    "Name",
    "(Name of Property Owners Association, (Association) and Phone Number)",
    "Other Broker Firm",
    "Other Brokers Address",
    "Phone",
    "Print Buyer(s) Name(s) [REQUIRED]",
    "Print Buyer(s) Name(s) [REQUIRED]",
    "Print Seller(s) Name(s) [REQUIRED]",
    "Phone/Fax",
    "Printed Name",
    "Printed Title",
    "Received by",
    "Seller",
    "Signature",
    "(Street Address and City)",
    "State",
    "Selling Associates Email Address",
    "Selling Associates Office Address",
    "Selling Associates Name",
    "Seller Signature",
    "State License #",
    "Sellers Designated Agent",
    "Sellers Attorney",
    "Team Name",
    "Work Phone",
    "Zip",
]
EMAIL_SIGNS = [
    "com",
    "net",
    "org",
    "edu",
    "gov",
    "ai",
    "biz",
    "info",
    "bz",
    "ca",
    "cn",
    "de",
    "es",
    "fi",
    "fr",
    "is",
    "it",
    "kr",
    "mx",
    "nl",
    "ro",
    "ru",
    "to",
    "uk",
    "us",
    "tr",
]
