"""A dictionary of season words in various languages.

Covers the following languages: English, French, Spanish, Portuguese, Hebrew, Arabic, Russian, Mandarin Chinese, Japanese, German, Bengali, Urdu, Telugu, Indonesian, Turkish, Hindi, Marathi, Tamil, Dutch, Italian, Polish, Swedish, Danish, Irish, Javanese, Korean, Gujarati, Ukranian.

FIXME: Cover more languages.
"""

seasonwords = {
    "spring": "03",
    "summer": "06",
    "autumn": "09",
    "fall": "09",
    "winter": "12",
    "printemps": "03",
    "primavera": "03",
    "primavera": "03",
    "אביב": "03",
    "الربيع": "03",
    "весна": "03",
    "春": "03",
    "Frühling": "03",
    "été": "06",
    "verano": "06",
    "verão": "06",
    "קיץ": "06",
    "الصيف": "06",
    "лето": "06",
    "夏": "06",
    "Sommer": "06",
    "automne": "09",
    "otoño": "09",
    "outono": "09",
    "סתיו": "09",
    "الخريف": "09",
    "осень": "09",
    "秋": "09",
    "Herbst": "09",
    "hiver": "12",
    "invierno": "12",
    "inverno": "12",
    "חורף": "12",
    "الشتاء": "12",
    "зима": "12",
    "冬": "12",
    "Winter": "12",
    "বসন্ত": "03",
    "بہار": "03",
    "春": "03",
    "వసంతం": "03",
    "Musim semi": "03",
    "İlkbahar": "03",
    "वसंत": "03",
    "वसंत": "03",
    "வசந்தகாலம்": "03",
    "গ্রীষ্ম": "06",
    "گرمی": "06",
    "夏": "06",
    "గ్రీష్మం": "06",
    "Musim panas": "06",
    "Yaz": "06",
    "ग्रीष्म": "06",
    "उन्हाळा": "06",
    "கோடைகாலம்": "06",
    "শরৎ": "09",
    "خزاں": "09",
    "秋": "09",
    "శరత్": "09",
    "Musim gugur": "09",
    "Sonbahar": "09",
    "शरद": "09",
    "शरद": "09",
    "இலையாக்காலம்": "09",
    "শীত": "12",
    "سردی": "12",
    "冬": "12",
    "శిశిరం": "12",
    "Musim dingin": "12",
    "Kış": "12",
    "शिशिर": "12",
    "हिवाळा": "12",
    "குளிர்காலம்": "12",
    "lente": "03",
    "primavera": "03",
    "wiosna": "03",
    "vår": "03",
    "forår": "03",
    "earrach": "03",
    "pring": "03",
    "봄": "03",
    "વસંત": "03",
    "весна": "03",
    "zomer": "06",
    "estate": "06",
    "lato": "06",
    "sommar": "06",
    "sommer": "06",
    "samhradh": "06",
    "panas": "06",
    "여름": "06",
    "ગ્રીષ્મ": "06",
    "літо": "06",
    "herfst": "09",
    "autunno": "09",
    "jesień": "09",
    "höst": "09",
    "efterår": "09",
    "fómhar": "09",
    "gugur": "09",
    "가을": "09",
    "શરદ": "09",
    "осінь": "09",
    "winter": "12",
    "inverno": "12",
    "zima": "12",
    "vinter": "12",
    "vinter": "12",
    "geimhreadh": "12",
    "pengarep": "12",
    "겨울": "12",
    "શિયાળો": "12",
    "зима": "12",
}
