import click

def single_quote(s: str) -> str: ...
def double_quote(s: str) -> str: ...
def resolve_ctx(
    cli: click.Command, prog_name: str, args: list[str], resilient_parsing: bool = True
) -> click.core.Context | None: ...
def split_args(line: str) -> list[str]: ...
def get_auto_shell() -> str: ...
