import click

def param_type_complete(
    self: click.ParamType, ctx: click.core.Context, incomplete: str
) -> list[tuple[str, str | None]]: ...
def choice_complete(
    self: click.Choice, ctx: click.core.Context, incomplete: str
) -> list[tuple[str, str | None]]: ...
def multicommand_get_command_short_help(
    self: click.MultiCommand, ctx: click.Context, cmd_name: str
) -> str: ...
def multicommand_get_command_hidden(
    self: click.MultiCommand, ctx: click.Context, cmd_name: str
) -> bool: ...
def _shellcomplete(
    cli: click.Command, prog_name: str, complete_var: str | None = None
) -> None: ...
def patch() -> None: ...
