from typing import Literal

def uplowcase(string: str, case: Literal["up", "low"]) -> str: ...
def capitalcase(string: str) -> str: ...
def camelcase(string: str) -> str: ...
def snakecase(string: str) -> str: ...
def spinalcase(string: str) -> str: ...
def pascalcase(string: str) -> str: ...
