
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-20T21:11:43-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d7baad8f9f5dd20b9a284d2231143f9e399f5c78",
 "version": "0.34.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
