# Generated by Django 5.1.1 on 2024-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbplayerstats",
            name="cnt_pfr_opp",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
