# Generated by Django 5.1.1 on 2024-09-17 15:46

import pkrdatamapper.common.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("players", "0006_alter_dbflopplayerstats_cnt_3bet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_3bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player 3bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_3bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to 3bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_4bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player 4+bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_4bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to 4+bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_cbet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player made a continuation bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_cbet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to make a c-bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_check",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player checked ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_check_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player check-raised ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_donk_bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player made a donk bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_donk_bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to make a donk bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_face_3bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a 3bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_face_4bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a 4+bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_face_cbet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a continuation bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_face_donk_bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a donk bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_face_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a raise ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_first_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player made the first raise ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_first_to_talk",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player was the first to talk ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_fold",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player folded ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_has_position",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had position ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_open",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player opened ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_open_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to open ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbflopplayerstats",
            name="cnt_saw",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player saw the street", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbgeneralplayerstats",
            name="cnt_is_hero",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player is the hero", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbgeneralplayerstats",
            name="cnt_went_to_showdown",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player went to showdown",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbgeneralplayerstats",
            name="cnt_won_hand",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player won the hand", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_3bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player 3bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_3bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player had the opportunity to 3bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_4bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player 4+bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_4bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player had the opportunity to 4+bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_blind_defense",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player defended the blinds ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_blind_defense_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player had the opportunity to defend the blinds ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_cold_called",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player cold called ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_face_3bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player faced a 3bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_face_4bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player faced a 4+bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_face_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player faced a raise ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_face_squeeze",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player faced a squeeze ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_face_steal_attempt",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player faced a steal attempt ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_first_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player made the first raise ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_fold",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player folded ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_fold_to_steal_attempt",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player folded to a steal attempt ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_limp",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player limped ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_open",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player opened ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_open_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player had the opportunity to open ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_open_shove",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player open shoved ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player raised ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_raise_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player had the opportunity to raise ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_squeeze",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player squeezed ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_squeeze_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player had the opportunity to squeeze ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_steal_attempt",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player attempted to steal ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_steal_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player had the opportunity to steal ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_voluntary_all_in",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player voluntarily went all in ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbpreflopplayerstats",
            name="cnt_vpip",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  the player voluntarily put money in the pot",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_3bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player 3bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_3bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to 3bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_4bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player 4+bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_4bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to 4+bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_cbet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player made a continuation bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_cbet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to make a c-bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_check",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player checked ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_check_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player check-raised ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_donk_bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player made a donk bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_donk_bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to make a donk bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_face_3bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a 3bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_face_4bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a 4+bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_face_cbet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a continuation bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_face_donk_bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a donk bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_face_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a raise ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_first_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player made the first raise ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_first_to_talk",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player was the first to talk ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_fold",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player folded ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_has_position",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had position ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_open",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player opened ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_open_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to open ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbriverplayerstats",
            name="cnt_saw",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player saw the street", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_3bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player 3bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_3bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to 3bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_4bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player 4+bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_4bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to 4+bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_cbet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player made a continuation bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_cbet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to make a c-bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_check",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player checked ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_check_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player check-raised ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_donk_bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player made a donk bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_donk_bet_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to make a donk bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_face_3bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a 3bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_face_4bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a 4+bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_face_cbet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a continuation bet ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_face_donk_bet",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a donk bet ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_face_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player faced a raise ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_first_raise",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player made the first raise ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_first_to_talk",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player was the first to talk ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_fold",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player folded ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_has_position",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had position ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_open",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player opened ", default=0
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_open_opportunity",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player had the opportunity to open ",
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="dbturnplayerstats",
            name="cnt_saw",
            field=pkrdatamapper.common.fields.CountField(
                db_comment="Count of hands where  player saw the street", default=0
            ),
        ),
    ]
