
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-23T08:51:39+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "520b8cd79f8fea52894d015e3df663ca078b4517",
 "version": "0.3.0rc84"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
