# Generated by Django 4.2.7 on 2024-09-20 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('kernel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhuankepinggujilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_zhuan_ke_ping_gu_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='zhuankepinggujilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='zhengzhuang',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='jian_yi_fang_an',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='建议方案'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_zhen_duan_ji_chu_li_yi_jian_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='zhen_duan',
            field=models.ManyToManyField(blank=True, related_name='zhen_duan', to='applications.zhenduan', verbose_name='诊断'),
        ),
        migrations.AddField(
            model_name='zhenduanjichuliyijianjilu',
            name='zheng_zhuang',
            field=models.ManyToManyField(blank=True, related_name='zheng_zhuang', to='applications.zhengzhuang', verbose_name='症状'),
        ),
        migrations.AddField(
            model_name='zhenduan',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='fu_wu_xiang_mu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='服务项目'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='ke_hu_lai_yuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.kehulaiyuan', verbose_name='客户来源'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_yu_yue_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='yuyuejilu',
            name='yu_yue_yi_sheng',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.operator', verbose_name='预约医生'),
        ),
        migrations.AddField(
            model_name='xiaofeijilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_xiao_fei_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='xiaofeijilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='ling_yong_ren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ling_yong_ren_wu_liao_tai_zhang', to='kernel.operator', verbose_name='领用人'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_wu_liao_tai_zhang', to='applications.material', verbose_name='物料'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='ru_chu_ku_cao_zuo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.ruchukucaozuo', verbose_name='入出库操作'),
        ),
        migrations.AddField(
            model_name='wuliaotaizhang',
            name='shi_yong_ren',
            field=models.ManyToManyField(blank=True, related_name='shi_yong_ren', to='kernel.operator', verbose_name='使用人'),
        ),
        migrations.AddField(
            model_name='suifangjilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_sui_fang_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='suifangjilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='shuiguangzhenzhiliaojilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_shui_guang_zhen_zhi_liao_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='shuiguangzhenzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='ruchukucaozuo',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='roudusuzhiliaojilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_rou_du_su_zhi_liao_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='roudusuzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='qianshuzhiqingtongyishujilu',
            name='fu_wu_xiang_mu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='服务项目'),
        ),
        migrations.AddField(
            model_name='qianshuzhiqingtongyishujilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_qian_shu_zhi_qing_tong_yi_shu_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='qianshuzhiqingtongyishujilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ke_hu_lai_yuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.kehulaiyuan', verbose_name='客户来源'),
        ),
        migrations.AddField(
            model_name='profile',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_Profile', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='material',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='kehulaiyuan',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='jiankangdiaochajilu',
            name='hun_fou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.hunfou', verbose_name='婚否'),
        ),
        migrations.AddField(
            model_name='jiankangdiaochajilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_jian_kang_diao_cha_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='jiankangdiaochajilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='hunfou',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='huangjinweizhenzhiliaojilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_huang_jin_wei_zhen_zhi_liao_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='huangjinweizhenzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='guosuanzhiliaojilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_guo_suan_zhi_liao_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='guosuanzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='guangzizhiliaojilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_guang_zi_zhi_liao_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='guangzizhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='fuwuleibie',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='fasongzhiliaozhuyishixiangjilu',
            name='fu_wu_xiang_mu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kernel.service', verbose_name='服务项目'),
        ),
        migrations.AddField(
            model_name='fasongzhiliaozhuyishixiangjilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_fa_song_zhi_liao_zhu_yi_shi_xiang_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='fasongzhiliaozhuyishixiangjilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='diaoqzhiliaojilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_diao_Q_zhi_liao_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='diaoqzhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='device',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='dengluqiandaojilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_deng_lu_qian_dao_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='dengluqiandaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='chongzhijilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_chong_zhi_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='chongzhijilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='chaoshengpaozhiliaojilu',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_set_chao_sheng_pao_zhi_liao_ji_lu', to='kernel.operator', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='chaoshengpaozhiliaojilu',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
        migrations.AddField(
            model_name='capital',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_pid', to='kernel.process', verbose_name='作业进程'),
        ),
    ]
