
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-22T23:21:38+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "0068ce5c22c9836a3c8a343d8f810b4d6bf5fcaf",
 "version": "0.10.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
