
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-09-19T11:51:29+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ac6c89525d31f95b6b184a9ad2d2aa57362300d",
 "version": "2.7.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
